//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.1008
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTWrapper.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BTWrapper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cu K 10K
        ///30  5  5  0  00  0  1  01   -4  +03 +15  +0.0d+0  1.0d+2  0.0  -1  +00  0
        ///  1.00D-04  0.0D-02   1.0  0.02D-00  0.001  0.00D-03  0.00D-05  0.002
        ///  3.0  -1.0D-01 -0.70D-01 0.7  0.001  -0.003  0.002   0.9  8977.58
        /// -0.0d-03  0.0D-05  0.0D-05  0.0  0.0  0.0  0.0 0.0  0.0   0.0  0.0  0.0  0.0  0.0 0.0 0.0
        ///    0  0  10.0   50.000   50.0   0.0   0.0   +0.00   +0.00  0.0  0.0  343.0  0.001  0  0  0  0
        ///    0   3  924.157    797.145     781.903  0.0  0.0  0.0
        ///    0   0.5   0.1   0.0   0.0   0.0   0  2 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BTinp_orig {
            get {
                return ResourceManager.GetString("BTinp_orig", resourceCulture);
            }
        }
        
        internal static byte[] smooth_exp {
            get {
                object obj = ResourceManager.GetObject("smooth_exp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] smooth_thr {
            get {
                object obj = ResourceManager.GetObject("smooth_thr", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
